# Generated by Django 2.1.2 on 2018-12-09 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0006_auto_20181209_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('rental_price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('days', models.FloatField(default=1)),
                ('pro_pic', models.ImageField(default='product/product_default.png', storage='/media/product', upload_to='')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.item_type')),
            ],
        ),
        migrations.CreateModel(
            name='rent_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('rented_on', models.DateTimeField(default=datetime.datetime(2018, 12, 9, 20, 55, 23, 500586))),
                ('return_date', models.DateTimeField(default=datetime.datetime(2018, 12, 9, 20, 55, 23, 500586))),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 9, 20, 55, 23, 500586))),
                ('created_by', models.CharField(default='User', max_length=20)),
                ('modified_by', models.CharField(default='User Modified', max_length=20)),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2018, 12, 9, 20, 55, 23, 500586))),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RentedBy', to='cart.customer')),
                ('item_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.items')),
                ('rented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rented', to='cart.customer')),
            ],
        ),
    ]
