# Generated by Django 2.1.2 on 2018-12-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='rent_details',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='rent_details',
            name='rented_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='rent_details',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
    ]
