# Generated by Django 2.1.2 on 2018-12-08 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='c_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profile/default-user.png', storage='/media/profile', upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=70)),
                ('report_count', models.IntegerField(default=0)),
                ('blacklist', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 466415))),
                ('created_by', models.CharField(default='User', max_length=20)),
                ('modified_by', models.CharField(default='User Modified', max_length=20)),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 466415))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 469406))),
                ('unitprice', models.FloatField(default=0, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('total_amount', models.FloatField(default=0, null=True)),
                ('status', models.IntegerField(default=-1)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 469406))),
                ('created_by', models.CharField(default='User', max_length=20)),
                ('modified_by', models.CharField(default='User Modified', max_length=20)),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 469406))),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='cart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='p_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=230)),
                ('price', models.FloatField()),
                ('pro_pic', models.ImageField(default='product/product_default.png', storage='/media/product', upload_to='')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 468408))),
                ('created_by', models.CharField(default='User', max_length=20)),
                ('modified_by', models.CharField(default='User Modified', max_length=20)),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 18, 15, 468408))),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.category')),
            ],
        ),
        migrations.CreateModel(
            name='profile_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchtext', models.CharField(max_length=20)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='seller_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerid', to='cart.customer')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerid', to='cart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='user_wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
            ],
        ),
        migrations.AddField(
            model_name='p_review',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cart.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='cart.customer'),
        ),
        migrations.AddField(
            model_name='c_review',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BUYER', to='cart.customer'),
        ),
        migrations.AddField(
            model_name='c_review',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SELLER', to='cart.customer'),
        ),
    ]
