# Generated by Django 2.1.1 on 2018-09-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
            ],
        ),
    ]
