# Generated by Django 2.1.1 on 2018-09-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_reviewe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cart.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
        ),
        migrations.AddField(
            model_name='p_reviewe',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
    ]
