# Generated by Django 2.1.1 on 2018-09-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180906_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='p_reviewe',
            new_name='p_review',
        ),
    ]
