# Generated by Django 2.1.2 on 2018-12-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20181209_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_review',
            name='review_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 693985)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 693985)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 21, 14, 32, 709638)),
        ),
    ]
