# Generated by Django 2.1.1 on 2018-09-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20180906_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='super_user',
        ),
    ]
