# Generated by Django 2.1.1 on 2018-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20181025_0234'),
        ('cart', '0026_auto_20181024_0228'),
    ]

    operations = [
    ]
