# Generated by Django 2.1.1 on 2018-10-24 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_auto_20181024_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_pic',
            field=models.ImageField(default='product/default-user.png', storage='/media/product', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='profile/default-user.png', storage='/media/profile', upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 20, 50, 13, 837109)),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cart.Product'),
        ),
        migrations.AlterField(
            model_name='p_review',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
    ]
